# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0174e18d74f30181c1c563bd7c31df4e7246f3f521f2161eeabb65ae99b07260af15acbc6aa5fe88c4c8e944c72cb0c9f1971ccd7a5b1fc782dc0ffcf017179

test:
  secret_key_base: cb7c7acb2da37cd4dcbfbdbf240d792b90b011e39d80b3a87d905f4313c5d34a984833532e4f1d225dca6af309de7d2afb52c0a803eb64ba7c6f67b4805abaf7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
